spring.application.name=geo-service

server.port=8082

# RF29 - Geolocalización Simplificada en Campus
# Zonas disponibles definidas en CampusZone enum

# Logging
logging.level.org.springframework.web=DEBUG
gamification.service.url = ${GAMIFICATION_SERVICE_URL:https://gamification-service.icysea-59b45732.eastus.azurecontainerapps.io}
