spring.application.name=geo-service

server.port=8082

# RF29 - Geolocalización Simplificada en Campus
# Zonas disponibles definidas en CampusZone enum

# Logging
logging.level.org.springframework.web=DEBUG
